# Generated by Django 3.0.4 on 2020-05-13 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='latitud',
            field=models.IntegerField(default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='longitud',
            field=models.IntegerField(default=0, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='tipo_terreno',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Tipo Terreno'),
            preserve_default=False,
        ),
    ]
