# Generated by Django 3.0.4 on 2020-05-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_auto_20200513_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='tipo_terreno',
            field=models.CharField(max_length=50, verbose_name='TipoTerreno'),
        ),
    ]
